import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import { getProductById } from "../data/marketplaceApi";
import { useCart, parsePrice, formatCurrency } from "../context/CartContext";
import { useAuth } from "../context/AuthContext";
import { MarketplaceProductVisual } from "../components/marketplace/MarketplaceProductVisual";
import { initializePaystackPayment } from "../api/marketplace";

function Icon({ name, size = 22 }) {
  const p={truck:<><path d="M3 6h11v11H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="19" r="1.7"/><circle cx="18" cy="19" r="1.7"/></>,pin:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.3"/></>,card:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h4"/></>,bank:<><path d="m3 9 9-5 9 5"/><path d="M5 10v7M9 10v7M15 10v7M19 10v7M3 19h18"/></>,phone:<><rect x="7" y="3" width="10" height="18" rx="2"/><path d="M11 18h2"/></>,shield:<path d="M12 3 20 6v5c0 5-3.3 8.7-8 10-4.7-1.3-8-5-8-10V6l8-3Z"/>,package:<><path d="m4 8 8-4 8 4v9l-8 4-8-4V8Z"/><path d="m4 8 8 4 8-4M12 12v9"/></>,cart:<><path d="M3 4h2l2.1 10.1a2 2 0 0 0 2 1.6h7.9a2 2 0 0 0 1.9-1.5L20.5 7H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>;
}
function Thumb({item}){ return <MarketplaceProductVisual product={item} size="checkout" /> }

function Option({selected,onClick,icon,title,description,disabled=false}){return <button type="button" disabled={disabled} onClick={onClick} className={"flex w-full items-center gap-4 rounded-[9px] border p-4 text-left "+(selected?"border-[#07863a] bg-[#f0fbf3]":"border-[#e0e6ed] bg-white")+(disabled?" cursor-not-allowed opacity-60":"")}><span className={"flex h-5 w-5 shrink-0 items-center justify-center rounded-full border-2 "+(selected?"border-[#07863a]":"border-[#b8c1d0]")}>{selected&&<span className="h-2.5 w-2.5 rounded-full bg-[#07863a]"/>}</span><Icon name={icon} size={27}/><span><strong className="block text-[14px] text-[#10183f]">{title}</strong><span className="text-[12px] text-[#69739a]">{description}</span></span></button>}
export default function CheckoutPage(){
 const {id}=useParams();const location=useLocation();const {items:cartItems,addItem}=useCart(); const {user}=useAuth();const [product,setProduct]=useState(null);const [delivery,setDelivery]=useState("delivery");const [address,setAddress]=useState(user?.location?.addressLine1 || ""); const [paymentLoading,setPaymentLoading]=useState(false); const [paymentError,setPaymentError]=useState("");
 useEffect(()=>{if(id)getProductById(id).then(setProduct)},[id]);
 const checkoutItems=id&&product?[{...product,quantity:Math.max(1, Number(location.state?.quantity) || 1)}]:cartItems;
 const subtotal=useMemo(()=>checkoutItems.reduce((sum,item)=>sum+Number(item.priceValue ?? parsePrice(item.price))*Number(item.quantity || 0),0),[checkoutItems]);
 const deliveryFee=delivery==="delivery"&&checkoutItems.length ? checkoutItems.reduce((sum,item)=>sum + (item.shipping?.homeDelivery ? Number(item.shipping?.deliveryFee || 0) * Number(item.quantity || 0) : 0),0) : 0; const total=subtotal+deliveryFee; const currencies=[...new Set(checkoutItems.map(item=>String(item.currency || "NGN").toUpperCase()))]; const hasMixedCurrencies=currencies.length>1;
 if(!checkoutItems.length)return <main className="flex min-h-[60vh] items-center justify-center"><div className="text-center"><h1 className="text-2xl font-bold text-[#10183f]">Your cart is empty</h1><Link to="/products" className="mt-4 inline-block text-[#07863a]">Continue shopping →</Link></div></main>;
 const primary=checkoutItems[0];
 async function payWithPaystack(){
  if(paymentLoading)return;
  setPaymentError("");
  if(hasMixedCurrencies){setPaymentError("Your cart contains multiple currencies. Please separate them before checkout.");return;}
  if(!address.trim()){setPaymentError("Enter your delivery address before continuing.");return;}
  const invalidItem=checkoutItems.find(item=>!(item.id || item._id || item.productId));
  if(invalidItem){setPaymentError("We could not identify one of the products in your cart. Refresh your cart and try again.");return;}
  setPaymentLoading(true);
  try{
   const result=await initializePaystackPayment({items:checkoutItems.map(item=>({productId:String(item.id || item._id || item.productId),quantity:Number(item.quantity || 1)})),deliveryMethod:"delivery",shippingAddress:{firstName:user?.firstName || "",lastName:user?.lastName || "",phone:user?.phone || "",addressLine1:address.trim(),city:user?.location?.city || "",state:user?.location?.state || "",country:user?.location?.country || "Nigeria"}});
   if(!result?.authorizationUrl)throw new Error("Paystack did not return a checkout link. Please try again.");
   window.location.assign(result.authorizationUrl);
  }catch(error){setPaymentError(error.message || "Unable to start payment. Please try again.");setPaymentLoading(false);}
 }
 return <main className="w-full bg-[#fbfcfd] px-4 pb-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1400px] pt-5">
  <nav className="mb-4 flex flex-wrap items-center gap-2 text-[12px] text-[#69739a]"><Link to="/">Home</Link><span>›</span><Link to="/products">Products</Link><span>›</span>{id?<><span>{primary.category}</span><span>›</span><span>{primary.title}</span><span>›</span></>:null}<span>{id?"Buy now":"Checkout"}</span></nav>
  <h1 className="text-[32px] font-bold tracking-[-0.045em] text-[#10183f]">{id?"Buy this product":"Checkout"}</h1><p className="text-[16px] text-[#69739a]">Review your item, delivery details, and payment information to complete your purchase.</p>
  <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.7fr)_minmax(360px,1fr)]"><div className="space-y-5">
   <section className="rounded-[10px] border border-[#e1e6ec] bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-[20px] font-bold text-[#10183f]">Product</h2>{id&&<Link to={"/products/"+primary.id} className="text-[14px] text-[#0759e8]">← Back to product</Link>}</div><div className="mt-4 space-y-3">{checkoutItems.map(item=><div key={item.id} className="flex flex-wrap items-center gap-5 rounded-[8px] border border-[#edf0f3] p-3"><Thumb item={item}/><div className="min-w-[200px] flex-1"><h3 className="text-[16px] font-semibold text-[#10183f]">{item.title}</h3><p className="mt-1 text-[22px] font-bold text-[#10183f]">{item.price}</p><p className="text-[12px] text-[#69739a]">Sold by {item.seller} · Qty: {item.quantity}</p><p className="mt-1 text-[12px] text-[#69739a]">{item.location}</p></div></div>)}</div></section>
   <section className="rounded-[10px] border border-[#e1e6ec] bg-white p-5"><h2 className="text-[20px] font-bold text-[#10183f]">Delivery information</h2><p className="text-[14px] text-[#69739a]">Choose how you want to receive your order.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Option selected={delivery==="delivery"} onClick={()=>setDelivery("delivery")} icon="truck" title="Deliver to my address" description="Get it delivered to your location"/><Option selected={delivery==="pickup"} onClick={()=>{}} disabled icon="package" title="Pick up from a nearby station" description="Not available yet. Confirmed pickup stations are not configured."/></div>{delivery==="delivery"&&<><div className="mt-4 flex items-start gap-3"><Icon name="pin" size={26}/><div className="min-w-0 flex-1"><strong className="block text-[14px] text-[#10183f]">{address || "Delivery address required"}</strong><span className="text-[12px] text-[#69739a]">{user?.location ? [user.location.city,user.location.state,user.location.country].filter(Boolean).join(", ") : "Add your delivery address to continue."}</span><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Enter your delivery address" className="mt-2 w-full rounded-[8px] border px-3 py-2 text-[13px]" /></div></div><div className="mt-4 rounded-[9px] bg-[#eaf9ee] p-4"><div className="flex gap-3 text-[#087d35]"><Icon name="truck" size={24}/><div><strong className="block text-[13px]">Estimated delivery: {primary.deliveryEstimate}</strong><span className="text-[11px] text-[#69739a]">Delivery fee will be calculated at checkout based on your location.</span></div></div></div></>}</section>
   <section className="rounded-[10px] border border-[#e1e6ec] bg-white p-5"><h2 className="text-[20px] font-bold text-[#10183f]">Pay securely with Paystack</h2><p className="mt-1 text-[14px] text-[#69739a]">You will be redirected to Paystack to choose an available payment method and complete payment securely. Matchet verifies the transaction before confirming your order.</p><div className="mt-4 flex items-center gap-3 rounded-lg bg-[#f4faf6] p-4"><Icon name="shield" size={28}/><div><strong className="block text-sm text-[#10183f]">Secure payment</strong><span className="text-xs text-[#69739a]">Your card or bank details are entered on Paystack, not stored by Matchet.</span></div></div></section>
  </div>
  <aside className="space-y-5"><section className="rounded-[10px] border border-[#e1e6ec] bg-white p-5"><h2 className="text-[22px] font-bold text-[#10183f]">Order summary</h2><div className="mt-4 space-y-3">{checkoutItems.map(item=><div key={item.id} className="flex gap-3"><Thumb item={item}/><div><h3 className="text-[14px] font-semibold">{item.title}</h3><p className="mt-1 text-[17px] font-bold">{formatCurrency(Number(item.priceValue ?? parsePrice(item.price))*Number(item.quantity || 0), item.currency || "NGN")}</p><p className="text-[11px] text-[#69739a]">Qty: {item.quantity}</p></div></div>)}</div><div className="mt-4 border-t pt-4 text-[14px]"><div className="flex justify-between"><span>Product total</span><strong>{formatCurrency(subtotal, primary?.currency || "NGN")}</strong></div><div className="mt-3 flex justify-between"><span>Delivery fee</span><strong>{formatCurrency(deliveryFee, primary?.currency || "NGN")}</strong></div><div className="mt-4 flex justify-between rounded-[8px] bg-[#eaf9ee] p-4 text-[18px] font-bold text-[#087d35]"><span>Total</span><span>{formatCurrency(total, primary?.currency || "NGN")}</span></div><button disabled={paymentLoading || hasMixedCurrencies || !address.trim()} onClick={payWithPaystack} className="mt-4 h-14 w-full rounded-[8px] bg-[#07863a] font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-400">{paymentLoading ? "Connecting to Paystack..." : "Pay securely with Paystack"}</button>{paymentError && <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">{paymentError}</p>}{hasMixedCurrencies && <p role="alert" className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Your cart contains multiple currencies. Separate currencies before checkout.</p>}{id&&<button onClick={()=>addItem(primary,1)} className="mt-3 flex h-12 w-full items-center justify-center gap-2 rounded-[8px] border border-[#07863a] text-[#07863a]"><Icon name="cart" size={19}/> Add to cart instead</button>}</div></section>
  <section className="rounded-[10px] border border-[#e1e6ec] bg-white p-5 space-y-4"><div className="flex gap-4"><Icon name="shield" size={28}/><div><strong>Secure checkout</strong><p className="text-[12px] text-[#69739a]">Your information is protected</p></div></div><div className="flex gap-4"><Icon name="package" size={28}/><div><strong>Easy returns</strong><p className="text-[12px] text-[#69739a]">Seller return policies apply</p></div></div></section>
  </aside></div></div></main>;
}