import {useEffect,useState} from "react";
import LocationSearch from "../components/LocationSearch";
import {useNavigate} from "react-router-dom";
import {ProviderShell,Icon} from "../components/ProviderShell";
import {getSellerProfile,updateSellerProfile} from "../api/provider";
import "../styles/seller-profile.css";
const date=v=>v?new Intl.DateTimeFormat("en-NG",{month:"long",year:"numeric"}).format(new Date(v)):"—";
export default function SellerProfile(){const[data,setData]=useState(null),[tab,setTab]=useState("store"),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
useEffect(()=>{getSellerProfile().then(r=>setData(r.data)).catch(e=>setMsg(e.message))},[]);
if(!data)return <ProviderShell mode="seller"><div className="sp-loading">{msg||"Loading profile..."}</div></ProviderShell>;
const s=data.store||{},u=data.user, c=data.completeness||{percentage:0,checks:[]};
const save=async e=>{e.preventDefault();setSaving(true);setMsg("");const f=new FormData(e.currentTarget);const payload={storeName:f.get("storeName"),description:f.get("description"),category:f.get("category"),location:{...(s.location||{}),...(f.get("location")?{city:f.get("location").split(",")[0]?.trim(),state:f.get("location").split(",")[1]?.trim()||"",country:f.get("location").split(",").slice(-1)[0]?.trim()||""}:{})}};try{const r=await updateSellerProfile(payload);setData({...data,store:{...s,...r.data}});setEditing(false);setMsg("Profile updated.");}catch(x){setMsg(x.message)}finally{setSaving(false)}};
return <ProviderShell mode="seller"><div className="seller-profile-page"><header className="sp-head"><div><h1>Profile</h1><p>Manage your store profile, brand information, and public details.</p></div><button onClick={()=>s.slug&&nav("/store/"+s.slug)}><Icon name="eye"/> View public store</button></header>
<section className="sp-hero"><div className="sp-avatar">{u.avatar?<img src={u.avatar} alt=""/>:<span>{u.firstName?.[0]}{u.lastName?.[0]}</span>}</div><div className="sp-hero-info"><h2>{u.name||"Your Store"} <Icon name="shield"/></h2><b>{s.storeName||"Store"}</b><span>⌖ {[s.location?.city,s.location?.country].filter(Boolean).join(", ")||"Location not set"}</span><p>{s.description||"Add a short description about your store."}</p><div className="sp-tags">{[s.category,...(s.onboardingData?.categories||[])].filter(Boolean).slice(0,5).map(x=><em key={x}>{x}</em>)}</div></div><button className="sp-edit" onClick={()=>setEditing(true)}><Icon name="edit"/> Edit profile</button></section>
<div className="sp-grid"><main><nav className="sp-tabs">{[["store","Store information"],["business","Business details"],["shipping","Shipping & policies"],["social","Social links"],["bank","Bank details"]].map(x=><button className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</nav>{editing?<form className="sp-card sp-form" onSubmit={save}><h2>Edit store information</h2><label>Store name<input name="storeName" defaultValue={s.storeName}/></label><label>Store category<input name="category" defaultValue={s.category}/></label><label>Store description<textarea name="description" defaultValue={s.description}/></label><label>Location<LocationSearch value={[s.location?.city,s.location?.state,s.location?.country].filter(Boolean).join(", ")} onSelect={(location)=>{ const input=document.querySelector("input[name=location]"); if(input) input.value=location.label; }} placeholder="Search for your city, state, or country..." /></label><input type="hidden" name="location" defaultValue={[s.location?.city,s.location?.state,s.location?.country].filter(Boolean).join(", ")} /><div className="sp-actions"><button type="button" onClick={()=>setEditing(false)}>Cancel</button><button type="submit" disabled={saving}>{saving?"Saving...":"Save changes"}</button></div></form>:<><section className="sp-card"><div className="sp-card-head"><div><h2>{tab==="store"?"Store information":tab==="business"?"Business details":tab==="shipping"?"Shipping & policies":tab==="social"?"Social links":"Bank details"}</h2><p>{tab==="store"?"Update your store's public information.":"Information supplied during seller onboarding."}</p></div><button onClick={()=>setEditing(true)}><Icon name="edit"/> Edit</button></div>{tab==="store"&&<div className="sp-details"><Row label="Store name" value={s.storeName}/><Row label="Store description" value={s.description||"Not added"}/><Row label="Store category" value={s.category||"Not added"}/><Row label="Location" value={[s.location?.city,s.location?.state,s.location?.country].filter(Boolean).join(", ")||"Not added"}/><Row label="Languages" value={(s.languages||[]).join(", ")||"Not added"}/><Row label="Member since" value={date(u.memberSince)}/></div>}{tab!=="store"&&<pre className="sp-json">{JSON.stringify(s[tab==="business"?"businessDetails":tab==="shipping"?"shippingPolicies":tab==="social"?"socialLinks":"payoutDetails"]||{},null,2)}</pre>}{tab==="store"&&s.banner?.url&&<div className="sp-banner"><img src={s.banner.url} alt="Store banner"/></div>}</section></>}</main>
<aside><section className="sp-card"><div className="sp-complete"><h2>Profile completeness <b>{c.percentage}%</b></h2><div className="sp-progress"><i style={{width:c.percentage+"%"}}/></div><p>Complete your profile to reach more customers.</p>{c.checks.map(x=><div className="sp-check" key={x.key}><span>{x.complete?"✓":"•"}</span>{x.label}{x.optional&&" (optional)"}</div>)}</div></section><section className="sp-card sp-photo"><h2>Profile photo</h2><div><div className="sp-small-avatar">{u.avatar?<img src={u.avatar} alt=""/>:<span>{u.firstName?.[0]}</span>}</div><p>This photo will be visible on your public store page.</p></div></section><section className="sp-card"><h2>Quick actions</h2>{["Edit profile","Manage products","View public store","Share store link"].map(x=><button className="sp-quick" key={x} onClick={()=>x==="Edit profile"?setEditing(true):x==="View public store"&&s.slug&&nav("/store/"+s.slug)}>{x}<span>›</span></button>)}</section><section className="sp-danger"><h2>Danger zone</h2><button>Deactivate store <span>›</span></button></section></aside></div>{msg&&<div className="sp-toast">{msg}</div>}</div></ProviderShell>}
function Row({label,value}){return <div className="sp-row"><b>{label}</b><span>{value||"Not added"}</span></div>}
