import {useEffect,useMemo,useState} from "react";
import {ProviderShell,Icon} from "../components/ProviderShell";
import {getSellerReviews} from "../api/provider";
import "../styles/seller-reviews.css";
const date=v=>new Intl.DateTimeFormat("en-NG",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v));
function Stars({rating}){return <span className="sr-stars">{[1,2,3,4,5].map(n=><b key={n} className={n<=rating?"on":""}>★</b>)}</span>}
export default function SellerReviews(){
 const [data,setData]=useState(null),[filter,setFilter]=useState("all"),[sort,setSort]=useState("newest"),[page,setPage]=useState(1),[search,setSearch]=useState("");
 useEffect(()=>{getSellerReviews().then(r=>setData(r.data)).catch(()=>setData({summary:{averageRating:0,totalReviews:0,positivePercentage:0,ratingBreakdown:[]},reviews:[]}))},[]);
 const reviews=useMemo(()=>{let a=[...(data?.reviews||[])];const q=search.toLowerCase().trim();if(filter!=="all")a=a.filter(r=>r.rating===Number(filter));if(q)a=a.filter(r=>(r.customer?.name+" "+r.product?.name+" "+r.comment).toLowerCase().includes(q));a.sort((x,y)=>sort==="oldest"?new Date(x.createdAt)-new Date(y.createdAt):sort==="highest"?y.rating-x.rating||new Date(y.createdAt)-new Date(x.createdAt):sort==="lowest"?x.rating-y.rating||new Date(y.createdAt)-new Date(x.createdAt):new Date(y.createdAt)-new Date(x.createdAt));return a},[data,filter,sort,search]);
 const per=5,count=Math.max(1,Math.ceil(reviews.length/per)),visible=reviews.slice((page-1)*per,page*per),s=data?.summary||{};
 useEffect(()=>setPage(1),[filter,sort,search]);
 return <ProviderShell mode="seller"><div className="seller-reviews-page">
  <header className="sr-head"><div><h1>Reviews</h1><p>See what your customers are saying and track your ratings.</p></div></header>
  <div className="sr-kpis"><K icon="star" value={s.averageRating||0} title="Average rating" sub={"From "+(s.totalReviews||0)+" reviews"}/><K icon="users" value={s.totalReviews||0} title="Total reviews" sub="All time"/><K icon="bag" value={(s.positivePercentage||0)+"%"} title="Would buy again" sub="Based on customer feedback"/><K icon="message" value={s.responseRate==null?"—":s.responseRate+"%"} title="Response rate" sub={s.responseRate==null?"No response data yet":"You reply to reviews"}/></div>
  <div className="sr-layout"><section className="sr-main">
   <div className="sr-tabs"><b>All reviews</b>{[5,4,3,2,1].map(r=><span key={r}>{r} stars ({s.ratingBreakdown?.find(x=>x.rating===r)?.count||0})</span>)}</div>
   <div className="sr-toolbar"><div className="sr-search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search reviews by customer, product, or keyword..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All ratings</option>{[5,4,3,2,1].map(r=><option key={r} value={r}>{r} stars</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="highest">Highest rating</option><option value="lowest">Lowest rating</option></select></div>
   {visible.length?<>{visible.map(r=><article className="sr-item" key={r.id}><div className="sr-avatar">{r.customer?.avatar?<img src={r.customer.avatar} alt=""/>:r.customer?.initials||"CU"}</div><div className="sr-customer"><strong>{r.customer?.name||"Customer"}</strong><small>{date(r.createdAt)}</small><Stars rating={r.rating}/></div><div className="sr-product">{r.product?.image&&<img src={r.product.image} alt=""/>}<div><strong>{r.product?.name||"Product"}</strong><p>{r.comment||"No written feedback provided."}</p></div></div><button>⋮</button></article>)}</>:<div className="sr-empty"><Icon name="star"/><strong>No reviews yet</strong><span>Customer reviews will appear here after they are published.</span></div>}
   <footer className="sr-footer"><span>Showing {reviews.length?(page-1)*per+1:0}–{Math.min(page*per,reviews.length)} of {reviews.length} reviews</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>‹</button>{Array.from({length:count},(_,i)=>i+1).slice(0,5).map(n=><button className={n===page?"active":""} key={n} onClick={()=>setPage(n)}>{n}</button>)}<button disabled={page===count} onClick={()=>setPage(page+1)}>›</button></div></footer>
  </section><aside>
   <section className="sr-card"><h2>Rating breakdown</h2>{[5,4,3,2,1].map(r=>{const x=s.ratingBreakdown?.find(v=>v.rating===r)||{count:0,percentage:0};return <div className="sr-bar" key={r}><span>{r} star{r===1?"":"s"}</span><i><em style={{width:x.percentage+"%"}}/></i><b>{x.count}</b></div>})}<div className="sr-positive"><Icon name="users"/><strong>{s.positivePercentage||0}%</strong><span>of customers would buy again</span></div></section>
   <section className="sr-card"><h2>Recent highlights</h2>{(data?.reviews||[]).filter(r=>r.comment?.trim()).slice(0,3).map(r=><div className="sr-highlight" key={r.id}>“{r.comment}”<small>{r.customer?.name||"Customer"}</small></div>)}{!(data?.reviews||[]).some(r=>r.comment?.trim())&&<div className="sr-no-highlight">No written highlights yet.</div>}<button className="sr-outline">View all reviews →</button></section>
  </aside></div>
 </div></ProviderShell>}
function K({icon,value,title,sub}){return <div className="sr-kpi"><i><Icon name={icon}/></i><strong>{value}</strong><b>{title}</b><span>{sub}</span></div>}
