import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ProviderShell, Icon } from "../components/ProviderShell";
import { getSellerProducts, createSellerProduct, updateSellerProduct } from "../api/provider";
import "../styles/seller-products.css";

const money=v=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(v||0));
const statusText=s=>({active:"Active",outOfStock:"Out of stock",draft:"Draft",archived:"Archived"}[s]||s);
const stockText=(p)=>p.inventory===0?"Out of stock":p.inventory<=5?"Low stock":"Active";

export default function SellerProducts(){
 const [data,setData]=useState(null),[tab,setTab]=useState("all"),[search,setSearch]=useState(""),[category,setCategory]=useState("all"),[sort,setSort]=useState("newest"),[selected,setSelected]=useState([]),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState({name:"",description:"",category:"",price:"",inventory:"",status:"draft"}),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=()=>getSellerProducts({status:tab,category,search,sort}).then(r=>setData(r.data)).catch(e=>setError(e.message||"Unable to load products."));
 useEffect(()=>{load()},[tab,category,search,sort]);
 const open=(p=null)=>{setEditing(p);setForm(p?{name:p.name,description:p.description,category:p.category,price:p.price,inventory:p.inventory,status:p.status}:{name:"",description:"",category:"",price:"",inventory:"",status:"draft"});setModal(true)};
 const save=async e=>{e.preventDefault();setSaving(true);setError("");try{const payload={...form,price:Number(form.price),inventory:Number(form.inventory)};editing?await updateSellerProduct(editing.id,payload):await createSellerProduct(payload);setModal(false);await load()}catch(e){setError(e.message||"Unable to save product.")}finally{setSaving(false)}};
 const products=data?.products||[],stats=data?.stats||{active:0,outOfStock:0,views:0,totalOrders:0,drafts:0,total:0};
 return <ProviderShell mode="seller"><div className="seller-products-page">
  <div className="seller-products-head"><div><h1>Products</h1><p>Manage your products, inventory, pricing, and listings.</p></div><button onClick={()=>open()}><Icon name="plus" size={17}/> Add a new product</button></div>
  <div className="product-stats">
   <div><i className="blue"><Icon name="grid"/></i><section><strong>{stats.active}</strong><b>Active products</b><span>Total listed</span></section></div>
   <div><i className="orange"><Icon name="grid"/></i><section><strong>{stats.outOfStock}</strong><b>Out of stock</b><span>Needs restocking</span></section></div>
   <div><i className="green"><Icon name="eye"/></i><section><strong>{stats.views.toLocaleString()}</strong><b>Total views</b><span>Last 30 days</span></section></div>
   <div><i className="purple"><Icon name="bag"/></i><section><strong>{stats.totalOrders}</strong><b>Total orders</b><span>All time</span></section></div>
  </div>
  <section className="products-table-card">
   <div className="product-tabs">{[["all","All products"],["active","Active"],["outOfStock","Out of stock"],["draft","Drafts"]].map(([k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{l}{k!=="all"&&<em>({k==="active"?stats.active:k==="outOfStock"?stats.outOfStock:stats.drafts})</em>}</button>)}</div>
   <div className="product-filters"><label><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..." /></label><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{(data?.categories||[]).map(c=><option key={c}>{c}</option>)}</select><select value={tab} onChange={e=>setTab(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="outOfStock">Out of stock</option><option value="draft">Drafts</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Sort by: Newest</option><option value="oldest">Oldest</option><option value="priceHigh">Highest price</option><option value="priceLow">Lowest price</option></select></div>
   <div className="product-table-wrap"><table><thead><tr><th><input type="checkbox" onChange={e=>setSelected(e.target.checked?products.map(p=>p.id):[])}/></th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Orders</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,p.id]:v.filter(x=>x!==p.id))}/></td><td><div className="product-cell">{p.image?<img src={p.image} alt=""/>:<span className="product-placeholder"><Icon name="grid"/></span>}<div><strong>{p.name}</strong><small>{p.description}</small></div></div></td><td>{p.category}</td><td><strong>{money(p.price)}</strong></td><td className={p.inventory===0?"zero":p.inventory<=5?"low":""}>{p.inventory}</td><td><span className={"product-pill "+p.status}>{statusText(p.status)}</span></td><td>{p.orders}</td><td><button className="edit-product" onClick={()=>open(p)}>Edit</button><button className="product-dots">⋮</button></td></tr>)}</tbody></table></div>
   {!products.length&&<div className="products-empty"><Icon name="grid" size={30}/><strong>No products found</strong><p>Add your first product or change the filters.</p><button onClick={()=>open()}>Add a new product</button></div>}
   <div className="products-footer"><span>Showing {products.length} of {stats.total} products</span><div><button>‹</button><button className="active-page">1</button><button>›</button></div></div>
  </section>
  {modal&&<div className="product-modal-backdrop"><form className="product-modal" onSubmit={save}><header><div><h2>{editing?"Edit product":"Add a new product"}</h2><p>{editing?"Update your product details and inventory.":"Create a product listing for your store."}</p></div><button type="button" onClick={()=>setModal(false)}>×</button></header>{error&&<div className="product-form-error">{error}</div>}<label>Product name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-two"><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Price<input required type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label></div><div className="form-two"><label>Inventory<input required type="number" min="0" value={form.inventory} onChange={e=>setForm({...form,inventory:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="active">Active</option><option value="outOfStock">Out of stock</option></select></label></div><footer><button type="button" onClick={()=>setModal(false)}>Cancel</button><button disabled={saving}>{saving?"Saving...":editing?"Save changes":"Create product"}</button></footer></form></div>}
 </div></ProviderShell>
}
