import {useEffect,useState} from "react";
import {useNavigate,useParams} from "react-router-dom";
import {ProviderShell,Icon} from "../components/ProviderShell";
import {getSellerProducts,createSellerProduct,updateSellerProduct} from "../api/provider";
import "../styles/seller-product-form.css";
const money=v=>v?new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(v)): "₦0";
export default function SellerProductForm(){const nav=useNavigate(),{productId}=useParams();const edit=Boolean(productId);const [loading,setLoading]=useState(edit),[saving,setSaving]=useState(false),[error,setError]=useState("");const [f,setF]=useState({name:"",shortDescription:"",description:"",category:"",price:"",inventory:"",status:"active",condition:"New",brand:"",material:"",weight:"",dimensions:"",color:"",tags:[],images:[]});
useEffect(()=>{if(!edit)return;getSellerProducts({search:""}).then(r=>{const p=(r.data.products||[]).find(x=>String(x.id)===String(productId));if(!p)throw new Error("Product not found.");setF(x=>({...x,name:p.name||"",shortDescription:p.shortDescription||p.description||"",description:p.description||"",category:p.category||"",price:p.price||"",inventory:p.inventory??"",status:p.status||"draft",sku:p.sku||"",...(p.details||{}),images:p.images||[]}))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[productId]);
const set=(k,v)=>setF(x=>({...x,[k]:v}));const addTag=e=>{if(e.key==="Enter"&&e.currentTarget.value.trim()){e.preventDefault();set("tags",[...f.tags,e.currentTarget.value.trim()]);e.currentTarget.value=""}};
const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");const payload={name:f.name,shortDescription:f.shortDescription,description:f.description,category:f.category,price:Number(f.price),inventory:Number(f.inventory),status:f.status,sku:f.sku,details:{condition:f.condition,brand:f.brand,material:f.material,weight:f.weight,dimensions:f.dimensions,color:f.color,tags:f.tags}};try{if(edit)await updateSellerProduct(productId,payload);else await createSellerProduct(payload);nav("/seller/products")}catch(x){setError(x.message||"Unable to save product.")}finally{setSaving(false)}};
if(loading)return <ProviderShell mode="seller"><div className="spf-loading">Loading product...</div></ProviderShell>;
return <ProviderShell mode="seller"><div className="seller-product-form"><button className="spf-back" onClick={()=>nav("/seller/products")}>← Back to products</button><header><div><h1>{edit?"Edit product":"Add a new product"}</h1><p>Provide accurate and detailed information to attract more customers.</p></div></header>{error&&<div className="spf-error">{error}</div>}<form onSubmit={submit}><main>
<section className="spf-card"><h2>Basic information</h2><p>Start with the essential details about your product.</p><div className="spf-two"><Field label="Product name *" value={f.name} set={v=>set("name",v)} placeholder="e.g. Handmade Woven Storage Basket"/><label>Category *<select required value={f.category} onChange={e=>set("category",e.target.value)}><option value="">Select a category</option>{["Home & Living","Kitchen & Dining","Fashion & Accessories","Beauty & Personal Care","Electronics","Health & Wellness","Other"].map(x=><option key={x}>{x}</option>)}</select></label></div><Field label="Short description *" value={f.shortDescription} set={v=>set("shortDescription",v)} placeholder="A brief description of your product" textarea/><Field label="Full description *" value={f.description} set={v=>set("description",v)} placeholder="Describe your product in detail. Include materials, dimensions, usage, care instructions, and anything else customers should know." textarea/></section>
<section className="spf-card"><h2>Product images</h2><p>Add high-quality images to showcase your product. You can add up to 6 images.</p><div className="spf-images">{Array.from({length:6}).map((_,i)=>{const img=f.images?.[i];return <label className="spf-image" key={i}>{img?.url?<img src={img.url} alt="" />:i===0&&<><b>＋</b><span>Add photos</span><small>JPG, PNG (Max 5MB)</small></>}<input type="file" accept="image/jpeg,image/png" disabled/><div className="spf-placeholder"><Icon name="grid"/></div></label>})}</div><small className="spf-note">Image storage/upload will be connected to the media service. The product record will not pretend an image was uploaded until that succeeds.</small></section>
<section className="spf-card"><h2>Pricing and inventory</h2><p>Set your price, stock quantity, and SKU (optional).</p><div className="spf-three"><Field label="Price (₦) *" value={f.price} set={v=>set("price",v)} type="number" placeholder="e.g. 12500"/><Field label="Stock quantity *" value={f.inventory} set={v=>set("inventory",v)} type="number" placeholder="e.g. 10"/><Field label="SKU (optional)" value={f.sku||""} set={v=>set("sku",v)} placeholder="e.g. BASKET-001"/></div></section>
</main><aside><section className="spf-card preview"><h2>Product preview</h2><div className="spf-preview"><div className="spf-preview-img">{f.images?.[0]?.url?<img src={f.images[0].url} alt="" />:<Icon name="grid"/>}</div><div><h3>{f.name||"Product name"}</h3><b>{money(f.price)}</b><div className="spf-stars">☆ ☆ ☆ ☆ ☆ <span>0 reviews</span></div><p>{f.shortDescription||"Short description will appear here."}</p></div></div></section><section className="spf-card"><h2>Additional details</h2><div className="spf-two"><label>Condition<select value={f.condition} onChange={e=>set("condition",e.target.value)}><option>New</option><option>Used</option><option>Refurbished</option></select></label><Field label="Brand (optional)" value={f.brand} set={v=>set("brand",v)} placeholder="e.g. IKEA, Handmade"/><Field label="Material (optional)" value={f.material} set={v=>set("material",v)} placeholder="e.g. Wood, Ceramic"/><Field label="Weight (optional)" value={f.weight} set={v=>set("weight",v)} placeholder="e.g. 1.2 kg"/><Field label="Dimensions (optional)" value={f.dimensions} set={v=>set("dimensions",v)} placeholder="e.g. 30 × 20 × 15 cm"/><Field label="Color (optional)" value={f.color} set={v=>set("color",v)} placeholder="e.g. Brown, Black"/></div><label>Tags (optional)<input placeholder="Add tags (press Enter)" onKeyDown={addTag}/></label>{f.tags.length>0&&<div className="spf-tags">{f.tags.map((x,i)=><button type="button" key={i} onClick={()=>set("tags",f.tags.filter((_,n)=>n!==i))}>{x} ×</button>)}</div></section><section className="spf-card"><h2>Visibility</h2><label>Product status *<select value={f.status} onChange={e=>set("status",e.target.value)}><option value="active">Active</option><option value="draft">Draft</option><option value="outOfStock">Out of stock</option></select></label><p className="spf-help">{f.status==="active"?"Your product will be visible to customers after publishing.":"This product will remain hidden until you publish it."}</p><div className="spf-actions"><button type="button" onClick={()=>set("status","draft")} disabled={saving}>Save as draft</button><button type="submit" disabled={saving}>{saving?"Saving...":f.status==="draft"?"Save product":"Publish product"}</button></div></section></aside></form></div></ProviderShell>}
function Field({label,value,set,placeholder,type="text",textarea=false}){return <label>{label}{textarea?<textarea required={label.includes("*")} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/>:<input required={label.includes("*")} type={type} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/>}</label>}
