import {useEffect,useState} from "react";
import {ProviderShell,Icon} from "../components/ProviderShell";
import {getSellerSettings,updateSellerSettingsPreferences,updateSellerSettingsStore} from "../api/provider";
import "../styles/seller-settings.css";
const labels=k=>k.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase());
export default function SellerSettings(){const[data,setData]=useState(null),[tab,setTab]=useState("account"),[msg,setMsg]=useState(""),[editing,setEditing]=useState(false);
useEffect(()=>{getSellerSettings().then(r=>setData(r.data)).catch(e=>setMsg(e.message))},[]);
if(!data)return <ProviderShell mode="seller"><div className="ss-loading">{msg||"Loading settings..."}</div></ProviderShell>;
const savePref=async(section,key,value)=>{setData(d=>({...d,[section]:{...d[section],[key]:value}}));try{await updateSellerSettingsPreferences({[section]:{[key]:value}});setMsg("Preference saved.");}catch(e){setMsg(e.message)}};
const saveStore=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const payload={store:{name:f.get("name"),category:f.get("category"),description:f.get("description")}};try{const r=await updateSellerSettingsStore(payload);setData(d=>({...d,store:{...d.store,name:r.data.store.storeName,category:r.data.store.category,description:r.data.store.description}}));setEditing(false);setMsg("Store settings saved.");}catch(e){setMsg(e.message)}};
const tabs=[["account","user","Account"],["notifications","bell","Notifications"],["payments","wallet","Payments"],["store","store","Store"],["shipping","truck","Shipping"],["privacy","lock","Privacy"],["platform","settings","Platform"]];
return <ProviderShell mode="seller"><div className="seller-settings-page"><header><div><h1>Settings</h1><p>Manage your account, preferences, and store settings.</p></div></header><nav className="ss-tabs">{tabs.map(([id,icon,name])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><Icon name={icon}/>{name}</button>)}</nav>
{tab==="account"&&<div className="ss-layout"><main className="ss-card"><h2>Account settings</h2><p className="ss-sub">Manage your basic account information and login preferences.</p><Row icon="message" title="Email address" desc="Used for login and important notifications" value={data.account.email} action="Change"/><Row icon="user" title="Phone number" desc="Used for account verification and alerts" value={data.account.phone||"Not configured"} action="Change"/><Row icon="settings" title="Password" desc="Keep your account secure" value="••••••••" action="Change"/><Row icon="settings" title="Language" desc="Choose your preferred language" value={data.platform.language||"English"}/><Row icon="user" title="Account status" desc="Your account status" value={data.account.isActive?"Active":"Inactive"}/><Row icon="shield" title="Seller application" desc="Current seller verification state" value={data.store.verificationStatus||"Not submitted"}/><Row icon="settings" title="Delete account" desc="Permanently delete your account and all associated data" action="Delete account" danger/></main><Side data={data}/></div>}
{tab==="notifications"&&<Pref title="Notification preferences" sub="Control how Matchet keeps you informed about your store." data={data.notifications} section="notifications" save={savePref}/>}
{tab==="payments"&&<div className="ss-card"><h2>Payment settings</h2><p className="ss-sub">Review the payout method associated with your seller account.</p><Row icon="wallet" title={data.payments.method?.bankName||"Payout method"} desc="Payout account" value={data.payments.method?.accountLast4?"•••• "+data.payments.method.accountLast4:"Not configured"} action="Edit"/><Row icon="shield" title="Verification" desc="Payout account verification state" value={data.payments.verificationStatus||"Not available"}/></div>}
{tab==="store"&&<div className="ss-card">{editing?<form onSubmit={saveStore}><h2>Store settings</h2><label>Store name<input name="name" defaultValue={data.store.name}/></label><label>Category<input name="category" defaultValue={data.store.category}/></label><label>Description<textarea name="description" defaultValue={data.store.description}/></label><div className="ss-actions"><button type="button" onClick={()=>setEditing(false)}>Cancel</button><button>Save changes</button></div></form>:<><div className="ss-title-row"><div><h2>Store settings</h2><p className="ss-sub">Manage your store information and public presence.</p></div><button onClick={()=>setEditing(true)}>Edit</button></div><Row icon="store" title="Store name" desc="Public store name" value={data.store.name||"Not configured"}/><Row icon="settings" title="Category" desc="Primary store category" value={data.store.category||"Not configured"}/><Row icon="message" title="Description" desc="Public store description" value={data.store.description||"Not configured"}/><Row icon="shield" title="Store status" desc="Current store state" value={data.store.status}/></>}</div>}
{tab==="shipping"&&<ObjectTab title="Shipping & policies" data={data.shipping} description="Manage shipping and delivery policies supplied for your store."/>}
{tab==="privacy"&&<Pref title="Data & privacy" sub="Control privacy preferences stored with your Matchet account." data={data.privacy} section="privacy" save={savePref}/>}
{tab==="platform"&&<div className="ss-layout"><main className="ss-card"><h2>Platform settings</h2><p className="ss-sub">Customize your Matchet experience.</p><SelectRow label="Dashboard view" value={data.platform.dashboardView||"Seller dashboard"}/><SelectRow label="Theme" value={data.platform.theme||"Light"}/><SelectRow label="Language" value={data.platform.language||"English"}/></main><Side data={data}/></div>}
{msg&&<div className="ss-toast">{msg}</div>}</div></ProviderShell>}
function Row({icon,title,desc,value,action,danger}){return <div className={"ss-row "+(danger?"danger":"")}><Icon name={icon}/><div><b>{title}</b><small>{desc}</small></div>{value!==undefined&&<span>{value}</span>}{action&&<button>{action}</button>}</div>}
function Pref({title,sub,data,section,save}){const entries=Object.entries(data||{});return <div className="ss-card"><h2>{title}</h2><p className="ss-sub">{sub}</p>{entries.length?entries.map(([k,v])=><div className="ss-pref" key={k}><div><b>{labels(k)}</b><small>Preference saved on your account</small></div><button className={"ss-toggle "+(v?"on":"")} onClick={()=>save(section,k,!v)}><i/></button></div>):<div className="ss-empty">No preferences configured yet.</div>}</div>}
function ObjectTab({title,data,description}){return <div className="ss-card"><h2>{title}</h2><p className="ss-sub">{description}</p><pre className="ss-json">{JSON.stringify(data||{},null,2)}</pre></div>}
function SelectRow({label,value}){return <div className="ss-select-row"><div><b>{label}</b><small>Saved platform preference</small></div><span>{value}⌄</span></div>}
function Side(){return <aside className="ss-side"><section className="ss-card"><h2>Account preferences</h2><p className="ss-sub">Customize your experience on Matchet.</p></section><section className="ss-card"><h2>Need help?</h2><p className="ss-sub">If you have questions about your settings, our support team is here to help.</p><button className="ss-help">Contact support →</button></section></aside>}
